# Generated by Django 5.1.6 on 2025-02-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='patientmedicalinfo',
            name='current_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalinfo',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
