# Generated by Django 5.1.6 on 2025-02-21 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctorprofile_user_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimage',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicalimages', to='api.patientprofile'),
        ),
    ]
